# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'car1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 565)
        MainWindow.setMinimumSize(QtCore.QSize(735, 565))
        MainWindow.setMaximumSize(QtCore.QSize(735, 565))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addB = QtWidgets.QPushButton(self.centralwidget)
        self.addB.setGeometry(QtCore.QRect(10, 340, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.addB.setFont(font)
        self.addB.setStyleSheet("    QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addB.setIcon(icon)
        self.addB.setObjectName("addB")
        self.listB = QtWidgets.QPushButton(self.centralwidget)
        self.listB.setGeometry(QtCore.QRect(10, 90, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.listB.setFont(font)
        self.listB.setStyleSheet("    QPushButton {\n"
"background-color: #F0F4EF ;\n"
"color: #3D2C29;\n"
"\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.listB.setIcon(icon1)
        self.listB.setObjectName("listB")
        self.editB = QtWidgets.QPushButton(self.centralwidget)
        self.editB.setGeometry(QtCore.QRect(10, 390, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.editB.setFont(font)
        self.editB.setStyleSheet("    QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editB.setIcon(icon2)
        self.editB.setObjectName("editB")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(150, -1, 561, 501))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("    QTabWidget {\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.tabWidget.setObjectName("tabWidget")
        self.list_page = QtWidgets.QWidget()
        self.list_page.setObjectName("list_page")
        self.list_table = QtWidgets.QTableWidget(self.list_page)
        self.list_table.setGeometry(QtCore.QRect(20, 70, 511, 311))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.list_table.setFont(font)
        self.list_table.setStyleSheet("    QTableWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.list_table.setObjectName("list_table")
        self.list_table.setColumnCount(4)
        self.list_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        item.setFont(font)
        self.list_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        item.setFont(font)
        self.list_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        item.setFont(font)
        self.list_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        item.setFont(font)
        self.list_table.setHorizontalHeaderItem(3, item)
        self.bg_log_2 = QtWidgets.QLabel(self.list_page)
        self.bg_log_2.setGeometry(QtCore.QRect(0, -100, 691, 771))
        self.bg_log_2.setStyleSheet("background-color: rgb(90, 90, 90)\n"
"")
        self.bg_log_2.setText("")
        self.bg_log_2.setPixmap(QtGui.QPixmap(":/newPrefix/9a707a7e883d3dd10376a3e1bf2ed4e8.jpg"))
        self.bg_log_2.setObjectName("bg_log_2")
        self.bg_log_2.raise_()
        self.list_table.raise_()
        self.tabWidget.addTab(self.list_page, "")
        self.add_page = QtWidgets.QWidget()
        self.add_page.setObjectName("add_page")
        self.box_add_1 = QtWidgets.QComboBox(self.add_page)
        self.box_add_1.setGeometry(QtCore.QRect(130, 310, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.box_add_1.setFont(font)
        self.box_add_1.setObjectName("box_add_1")
        self.box_add_1.addItem("")
        self.box_add_1.addItem("")
        self.box_add_1.addItem("")
        self.price_in_1 = QtWidgets.QLineEdit(self.add_page)
        self.price_in_1.setGeometry(QtCore.QRect(350, 350, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.price_in_1.setFont(font)
        self.price_in_1.setObjectName("price_in_1")
        self.saveB_1 = QtWidgets.QPushButton(self.add_page)
        self.saveB_1.setGeometry(QtCore.QRect(180, 400, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.saveB_1.setFont(font)
        self.saveB_1.setStyleSheet("    QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.saveB_1.setObjectName("saveB_1")
        self.label_4 = QtWidgets.QLabel(self.add_page)
        self.label_4.setGeometry(QtCore.QRect(260, 350, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("    QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.model = QtWidgets.QLabel(self.add_page)
        self.model.setGeometry(QtCore.QRect(40, 350, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.model.setFont(font)
        self.model.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.model.setStyleSheet("    QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.model.setAlignment(QtCore.Qt.AlignCenter)
        self.model.setObjectName("mc")
        self.label_5 = QtWidgets.QLabel(self.add_page)
        self.label_5.setGeometry(QtCore.QRect(40, 310, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("    QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.photo_1 = QtWidgets.QLabel(self.add_page)
        self.photo_1.setGeometry(QtCore.QRect(80, 20, 361, 271))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.photo_1.setFont(font)
        self.photo_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.photo_1.setStyleSheet("    QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.photo_1.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_1.setObjectName("photo_1")
        self.bg_add = QtWidgets.QLabel(self.add_page)
        self.bg_add.setGeometry(QtCore.QRect(-10, -130, 831, 781))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bg_add.setFont(font)
        self.bg_add.setStyleSheet("background-color: #6C757D ;\n"
"color: #2C3E50;")
        self.bg_add.setText("")
        self.bg_add.setPixmap(QtGui.QPixmap(":/newPrefix/19eee91f32a591a52ce1b92e1fa092f9.jpg"))
        self.bg_add.setObjectName("bg_add")
        self.label_9 = QtWidgets.QLabel(self.add_page)
        self.label_9.setGeometry(QtCore.QRect(260, 310, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setStyleSheet("    QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.box_add_2 = QtWidgets.QComboBox(self.add_page)
        self.box_add_2.setGeometry(QtCore.QRect(130, 350, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.box_add_2.setFont(font)
        self.box_add_2.setObjectName("box_add_2")
        self.box_add_2.addItem("")
        self.box_add_2.addItem("")
        self.box_add_2.addItem("")
        self.name_in_1 = QtWidgets.QLineEdit(self.add_page)
        self.name_in_1.setGeometry(QtCore.QRect(350, 310, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name_in_1.setFont(font)
        self.name_in_1.setObjectName("name_in_1")
        self.bg_add.raise_()
        self.box_add_1.raise_()
        self.price_in_1.raise_()
        self.saveB_1.raise_()
        self.label_4.raise_()
        self.model.raise_()
        self.label_5.raise_()
        self.photo_1.raise_()
        self.label_9.raise_()
        self.box_add_2.raise_()
        self.name_in_1.raise_()
        self.tabWidget.addTab(self.add_page, "")
        self.edit_page = QtWidgets.QWidget()
        self.edit_page.setObjectName("edit_page")
        self.searchB = QtWidgets.QPushButton(self.edit_page)
        self.searchB.setGeometry(QtCore.QRect(100, 100, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchB.setFont(font)
        self.searchB.setStyleSheet("    QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.searchB.setObjectName("searchB")
        self.deleteB = QtWidgets.QPushButton(self.edit_page)
        self.deleteB.setGeometry(QtCore.QRect(100, 200, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.deleteB.setFont(font)
        self.deleteB.setStyleSheet("    QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.deleteB.setObjectName("deleteB")
        self.bg_edit = QtWidgets.QLabel(self.edit_page)
        self.bg_edit.setGeometry(QtCore.QRect(-100, -140, 871, 691))
        self.bg_edit.setStyleSheet("background-color: #6C757D ;\n"
"color: #2C3E50;")
        self.bg_edit.setText("")
        self.bg_edit.setPixmap(QtGui.QPixmap(":/newPrefix/889d0311af25dd85e87efb8f968b1d90.jpg"))
        self.bg_edit.setObjectName("bg_edit")
        self.label_49 = QtWidgets.QLabel(self.edit_page)
        self.label_49.setGeometry(QtCore.QRect(10, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_49.setStyleSheet("    QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.car_search = QtWidgets.QLineEdit(self.edit_page)
        self.car_search.setGeometry(QtCore.QRect(90, 30, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.car_search.setFont(font)
        self.car_search.setObjectName("car_search")
        self.box_edit_1 = QtWidgets.QComboBox(self.edit_page)
        self.box_edit_1.setGeometry(QtCore.QRect(150, 310, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.box_edit_1.setFont(font)
        self.box_edit_1.setObjectName("box_edit_1")
        self.box_edit_1.addItem("")
        self.box_edit_1.addItem("")
        self.box_edit_1.addItem("")
        self.label_23 = QtWidgets.QLabel(self.edit_page)
        self.label_23.setGeometry(QtCore.QRect(60, 310, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_23.setStyleSheet("    QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.model_2 = QtWidgets.QLabel(self.edit_page)
        self.model_2.setGeometry(QtCore.QRect(60, 350, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.model_2.setFont(font)
        self.model_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.model_2.setStyleSheet("    QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.model_2.setAlignment(QtCore.Qt.AlignCenter)
        self.model_2.setObjectName("model_2")
        self.box_edit_3 = QtWidgets.QComboBox(self.edit_page)
        self.box_edit_3.setGeometry(QtCore.QRect(150, 350, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.box_edit_3.setFont(font)
        self.box_edit_3.setObjectName("box_edit_3")
        self.box_edit_3.addItem("")
        self.box_edit_3.addItem("")
        self.box_edit_3.addItem("")
        self.label_22 = QtWidgets.QLabel(self.edit_page)
        self.label_22.setGeometry(QtCore.QRect(280, 350, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_22.setStyleSheet("    QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.photo_2 = QtWidgets.QLabel(self.edit_page)
        self.photo_2.setGeometry(QtCore.QRect(260, 30, 271, 211))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.photo_2.setFont(font)
        self.photo_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.photo_2.setStyleSheet("    QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.photo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_2.setObjectName("photo_2")
        self.price_in_2 = QtWidgets.QLineEdit(self.edit_page)
        self.price_in_2.setGeometry(QtCore.QRect(370, 350, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.price_in_2.setFont(font)
        self.price_in_2.setObjectName("price_in_2")
        self.name_in_4 = QtWidgets.QLineEdit(self.edit_page)
        self.name_in_4.setGeometry(QtCore.QRect(370, 310, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name_in_4.setFont(font)
        self.name_in_4.setObjectName("name_in_4")
        self.label_15 = QtWidgets.QLabel(self.edit_page)
        self.label_15.setGeometry(QtCore.QRect(280, 310, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setStyleSheet("    QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.saveB_3 = QtWidgets.QPushButton(self.edit_page)
        self.saveB_3.setGeometry(QtCore.QRect(100, 150, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.saveB_3.setFont(font)
        self.saveB_3.setStyleSheet("    QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.saveB_3.setObjectName("saveB_3")
        self.bg_edit.raise_()
        self.searchB.raise_()
        self.deleteB.raise_()
        self.label_49.raise_()
        self.car_search.raise_()
        self.box_edit_1.raise_()
        self.label_23.raise_()
        self.model_2.raise_()
        self.box_edit_3.raise_()
        self.label_22.raise_()
        self.photo_2.raise_()
        self.price_in_2.raise_()
        self.name_in_4.raise_()
        self.label_15.raise_()
        self.saveB_3.raise_()
        self.tabWidget.addTab(self.edit_page, "")
        self.playlist_page = QtWidgets.QWidget()
        self.playlist_page.setObjectName("playlist_page")
        self.search_table = QtWidgets.QTableWidget(self.playlist_page)
        self.search_table.setGeometry(QtCore.QRect(20, 30, 511, 301))
        self.search_table.setStyleSheet("    QTableWidget {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.search_table.setObjectName("search_table")
        self.search_table.setColumnCount(4)
        self.search_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.search_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.search_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.search_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.search_table.setHorizontalHeaderItem(3, item)
        self.searchB_4 = QtWidgets.QPushButton(self.playlist_page)
        self.searchB_4.setGeometry(QtCore.QRect(370, 370, 81, 31))
        self.searchB_4.setStyleSheet("    QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.searchB_4.setObjectName("searchB_4")
        self.box_search_1 = QtWidgets.QComboBox(self.playlist_page)
        self.box_search_1.setGeometry(QtCore.QRect(10, 370, 81, 31))
        self.box_search_1.setStyleSheet("    QComboBox {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.box_search_1.setObjectName("box_search_1")
        self.box_search_1.addItem("")
        self.box_search_2 = QtWidgets.QComboBox(self.playlist_page)
        self.box_search_2.setGeometry(QtCore.QRect(100, 370, 81, 31))
        self.box_search_2.setStyleSheet("    QComboBox {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.box_search_2.setObjectName("box_search_2")
        self.box_search_2.addItem("")
        self.bg_play = QtWidgets.QLabel(self.playlist_page)
        self.bg_play.setGeometry(QtCore.QRect(-20, -50, 831, 781))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bg_play.setFont(font)
        self.bg_play.setStyleSheet("background-color: #6C757D ;\n"
"color: #2C3E50;")
        self.bg_play.setText("")
        self.bg_play.setPixmap(QtGui.QPixmap(":/newPrefix/19eee91f32a591a52ce1b92e1fa092f9.jpg"))
        self.bg_play.setObjectName("bg_play")
        self.box_search_4 = QtWidgets.QComboBox(self.playlist_page)
        self.box_search_4.setGeometry(QtCore.QRect(280, 370, 81, 31))
        self.box_search_4.setStyleSheet("    QComboBox {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.box_search_4.setObjectName("box_search_4")
        self.box_search_4.addItem("")
        self.box_search_3 = QtWidgets.QComboBox(self.playlist_page)
        self.box_search_3.setGeometry(QtCore.QRect(190, 370, 81, 31))
        self.box_search_3.setStyleSheet("    QComboBox {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.box_search_3.setObjectName("box_search_3")
        self.box_search_3.addItem("")
        self.bookB = QtWidgets.QPushButton(self.playlist_page)
        self.bookB.setGeometry(QtCore.QRect(460, 370, 81, 31))
        self.bookB.setStyleSheet("    QPushButton {\n"
"    background-color: Red;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.bookB.setObjectName("bookB")
        self.bg_play.raise_()
        self.search_table.raise_()
        self.searchB_4.raise_()
        self.box_search_1.raise_()
        self.box_search_2.raise_()
        self.box_search_4.raise_()
        self.box_search_3.raise_()
        self.bookB.raise_()
        self.tabWidget.addTab(self.playlist_page, "")
        self.profile_page = QtWidgets.QWidget()
        self.profile_page.setObjectName("profile_page")
        self.user_label = QtWidgets.QLabel(self.profile_page)
        self.user_label.setGeometry(QtCore.QRect(10, 360, 171, 31))
        self.user_label.setStyleSheet("    QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.user_label.setObjectName("user_label")
        self.profile_table = QtWidgets.QTableWidget(self.profile_page)
        self.profile_table.setGeometry(QtCore.QRect(10, 10, 541, 341))
        self.profile_table.setObjectName("profile_table")
        self.profile_table.setColumnCount(0)
        self.profile_table.setRowCount(0)
        self.rents_label = QtWidgets.QLabel(self.profile_page)
        self.rents_label.setGeometry(QtCore.QRect(210, 360, 141, 31))
        self.rents_label.setStyleSheet("    QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.rents_label.setObjectName("rents_label")
        self.logoutB = QtWidgets.QPushButton(self.profile_page)
        self.logoutB.setGeometry(QtCore.QRect(380, 400, 141, 31))
        self.logoutB.setStyleSheet("    QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.logoutB.setObjectName("logoutB")
        self.bg_profile = QtWidgets.QLabel(self.profile_page)
        self.bg_profile.setGeometry(QtCore.QRect(-10, -20, 811, 691))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.bg_profile.setFont(font)
        self.bg_profile.setStyleSheet("background-color: #6C757D ;\n"
"color: #2C3E50;")
        self.bg_profile.setText("")
        self.bg_profile.setPixmap(QtGui.QPixmap(":/newPrefix/889d0311af25dd85e87efb8f968b1d90.jpg"))
        self.bg_profile.setObjectName("bg_profile")
        self.amount_label = QtWidgets.QLabel(self.profile_page)
        self.amount_label.setGeometry(QtCore.QRect(380, 360, 141, 31))
        self.amount_label.setStyleSheet("    QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.amount_label.setObjectName("amount_label")
        self.bg_profile.raise_()
        self.user_label.raise_()
        self.profile_table.raise_()
        self.rents_label.raise_()
        self.logoutB.raise_()
        self.amount_label.raise_()
        self.tabWidget.addTab(self.profile_page, "")
        self.log_page = QtWidgets.QWidget()
        self.log_page.setObjectName("log_page")
        self.label = QtWidgets.QLabel(self.log_page)
        self.label.setGeometry(QtCore.QRect(180, 80, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("    QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.log_page)
        self.label_2.setGeometry(QtCore.QRect(180, 150, 81, 31))
        self.label_2.setStyleSheet("    QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_16 = QtWidgets.QLabel(self.log_page)
        self.label_16.setGeometry(QtCore.QRect(180, 190, 81, 31))
        self.label_16.setStyleSheet("    QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.log_page)
        self.label_18.setGeometry(QtCore.QRect(180, 230, 81, 31))
        self.label_18.setStyleSheet("    QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.name_in = QtWidgets.QLineEdit(self.log_page)
        self.name_in.setGeometry(QtCore.QRect(290, 150, 171, 31))
        self.name_in.setObjectName("name_in")
        self.email_in = QtWidgets.QLineEdit(self.log_page)
        self.email_in.setGeometry(QtCore.QRect(290, 190, 171, 31))
        self.email_in.setObjectName("email_in")
        self.bg_log = QtWidgets.QLabel(self.log_page)
        self.bg_log.setGeometry(QtCore.QRect(-20, -290, 751, 751))
        self.bg_log.setStyleSheet("/* Background: Light Mint, Text: Deep Charcoal */\n"
"background-color: #6C757D ;\n"
"color: #2C3E50;\n"
"")
        self.bg_log.setText("")
        self.bg_log.setObjectName("bg_log")
        self.logB = QtWidgets.QPushButton(self.log_page)
        self.logB.setGeometry(QtCore.QRect(180, 280, 281, 31))
        self.logB.setStyleSheet("    QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.logB.setObjectName("logB")
        self.password_in = QtWidgets.QLineEdit(self.log_page)
        self.password_in.setGeometry(QtCore.QRect(290, 230, 171, 31))
        self.password_in.setObjectName("password_in")
        self.bg_log.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_16.raise_()
        self.label_18.raise_()
        self.name_in.raise_()
        self.email_in.raise_()
        self.logB.raise_()
        self.password_in.raise_()
        self.tabWidget.addTab(self.log_page, "")
        self.loginB = QtWidgets.QPushButton(self.centralwidget)
        self.loginB.setGeometry(QtCore.QRect(10, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.loginB.setFont(font)
        self.loginB.setStyleSheet("    QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }")
        self.loginB.setObjectName("loginB")
        self.searchB_3 = QtWidgets.QPushButton(self.centralwidget)
        self.searchB_3.setGeometry(QtCore.QRect(10, 130, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.searchB_3.setFont(font)
        self.searchB_3.setStyleSheet("    QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../Downloads/icons8-playlist-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchB_3.setIcon(icon3)
        self.searchB_3.setObjectName("searchB_3")
        self.profileB = QtWidgets.QPushButton(self.centralwidget)
        self.profileB.setGeometry(QtCore.QRect(10, 170, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.profileB.setFont(font)
        self.profileB.setStyleSheet("    QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../Downloads/icons8-account-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profileB.setIcon(icon4)
        self.profileB.setObjectName("profileB")
        self.bg_win1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_win1.setGeometry(QtCore.QRect(-130, -80, 901, 981))
        self.bg_win1.setAutoFillBackground(False)
        self.bg_win1.setStyleSheet("background-color: #0A1828;\n"
"color: #3D2C29;")
        self.bg_win1.setText("")
        self.bg_win1.setObjectName("bg_win1")
        self.bg_head = QtWidgets.QLabel(self.centralwidget)
        self.bg_head.setGeometry(QtCore.QRect(-120, -40, 251, 581))
        self.bg_head.setStyleSheet("background-color: rgb(168, 60, 50)")
        self.bg_head.setText("")
        self.bg_head.setObjectName("bg_head")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(20, 300, 81, 21))
        self.label_20.setStyleSheet("QLabel{\n"
"    background-color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"    }\n"
"")
        self.label_20.setObjectName("label_20")
        self.bg_win1.raise_()
        self.bg_head.raise_()
        self.addB.raise_()
        self.listB.raise_()
        self.editB.raise_()
        self.tabWidget.raise_()
        self.loginB.raise_()
        self.searchB_3.raise_()
        self.profileB.raise_()
        self.label_20.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 735, 26))
        self.menubar.setObjectName("menubar")
        self.menuBackground = QtWidgets.QMenu(self.menubar)
        self.menuBackground.setObjectName("menuBackground")
        self.menuCustom = QtWidgets.QMenu(self.menuBackground)
        self.menuCustom.setObjectName("menuCustom")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSimple = QtWidgets.QAction(MainWindow)
        self.actionSimple.setObjectName("actionSimple")
        self.actionsign_in = QtWidgets.QAction(MainWindow)
        self.actionsign_in.setObjectName("actionsign_in")
        self.actionview = QtWidgets.QAction(MainWindow)
        self.actionview.setObjectName("actionview")
        self.actionadd = QtWidgets.QAction(MainWindow)
        self.actionadd.setObjectName("actionadd")
        self.actionedit = QtWidgets.QAction(MainWindow)
        self.actionedit.setObjectName("actionedit")
        self.actionplaylist = QtWidgets.QAction(MainWindow)
        self.actionplaylist.setObjectName("actionplaylist")
        self.actionprofile = QtWidgets.QAction(MainWindow)
        self.actionprofile.setObjectName("actionprofile")
        self.actionDefault = QtWidgets.QAction(MainWindow)
        self.actionDefault.setObjectName("actionDefault")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.menuCustom.addAction(self.actionsign_in)
        self.menuCustom.addAction(self.actionview)
        self.menuCustom.addAction(self.actionadd)
        self.menuCustom.addAction(self.actionedit)
        self.menuCustom.addAction(self.actionplaylist)
        self.menuCustom.addAction(self.actionprofile)
        self.menuBackground.addAction(self.actionDefault)
        self.menuBackground.addAction(self.actionSimple)
        self.menuBackground.addAction(self.menuCustom.menuAction())
        self.menuMenu.addAction(self.actionAbout)
        self.menuMenu.addAction(self.actionHelp)
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuBackground.menuAction())
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addB.setText(_translate("MainWindow", " Add Car"))
        self.listB.setText(_translate("MainWindow", "List of cars"))
        self.editB.setText(_translate("MainWindow", " Edit Car"))
        item = self.list_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type"))
        item = self.list_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Model"))
        item = self.list_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.list_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Price"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.list_page), _translate("MainWindow", "Page"))
        self.box_add_1.setItemText(0, _translate("MainWindow", "SUV"))
        self.box_add_1.setItemText(1, _translate("MainWindow", "Crossover"))
        self.box_add_1.setItemText(2, _translate("MainWindow", "Sedan"))
        self.saveB_1.setText(_translate("MainWindow", "Save"))
        self.label_4.setText(_translate("MainWindow", "Price"))
        self.model.setText(_translate("MainWindow", "Model"))
        self.label_5.setText(_translate("MainWindow", "Type"))
        self.photo_1.setText(_translate("MainWindow", "Photo:"))
        self.label_9.setText(_translate("MainWindow", "Name"))
        self.box_add_2.setItemText(0, _translate("MainWindow", "Hyundai"))
        self.box_add_2.setItemText(1, _translate("MainWindow", "Honda"))
        self.box_add_2.setItemText(2, _translate("MainWindow", "Lexus"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.add_page), _translate("MainWindow", "Page"))
        self.searchB.setText(_translate("MainWindow", "Search"))
        self.deleteB.setText(_translate("MainWindow", "Delete"))
        self.label_49.setText(_translate("MainWindow", "Car"))
        self.box_edit_1.setItemText(0, _translate("MainWindow", "SUV"))
        self.box_edit_1.setItemText(1, _translate("MainWindow", "Crossover"))
        self.box_edit_1.setItemText(2, _translate("MainWindow", "Sedan"))
        self.label_23.setText(_translate("MainWindow", "Type"))
        self.model_2.setText(_translate("MainWindow", "Model"))
        self.box_edit_3.setItemText(0, _translate("MainWindow", "Hyundai"))
        self.box_edit_3.setItemText(1, _translate("MainWindow", "Honda"))
        self.box_edit_3.setItemText(2, _translate("MainWindow", "Lexus"))
        self.label_22.setText(_translate("MainWindow", "Price"))
        self.photo_2.setText(_translate("MainWindow", "Photo:"))
        self.label_15.setText(_translate("MainWindow", "Name"))
        self.saveB_3.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.edit_page), _translate("MainWindow", "Page"))
        item = self.search_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type"))
        item = self.search_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Model"))
        item = self.search_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.search_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Price"))
        self.searchB_4.setText(_translate("MainWindow", "Search"))
        self.box_search_1.setItemText(0, _translate("MainWindow", "Type"))
        self.box_search_2.setItemText(0, _translate("MainWindow", "Model"))
        self.box_search_4.setItemText(0, _translate("MainWindow", "Price"))
        self.box_search_3.setItemText(0, _translate("MainWindow", "Name"))
        self.bookB.setText(_translate("MainWindow", "Book"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.playlist_page), _translate("MainWindow", "Page"))
        self.user_label.setText(_translate("MainWindow", "Welcome UserName !"))
        self.rents_label.setText(_translate("MainWindow", "No. Rents/Users"))
        self.logoutB.setText(_translate("MainWindow", "Log Out"))
        self.amount_label.setText(_translate("MainWindow", "Amount/ Rents"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.profile_page), _translate("MainWindow", "Page"))
        self.label.setText(_translate("MainWindow", "Log in / Sign up"))
        self.label_2.setText(_translate("MainWindow", "Name:"))
        self.label_16.setText(_translate("MainWindow", "Email:"))
        self.label_18.setText(_translate("MainWindow", "Password:"))
        self.logB.setText(_translate("MainWindow", "Enter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log_page), _translate("MainWindow", "Page"))
        self.loginB.setText(_translate("MainWindow", "Log In"))
        self.searchB_3.setText(_translate("MainWindow", "Search"))
        self.profileB.setText(_translate("MainWindow", " Profile"))
        self.label_20.setText(_translate("MainWindow", "For Admin:"))
        self.menuBackground.setTitle(_translate("MainWindow", "Background"))
        self.menuCustom.setTitle(_translate("MainWindow", "Custom"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionSimple.setText(_translate("MainWindow", "Simple"))
        self.actionsign_in.setText(_translate("MainWindow", "sign in"))
        self.actionview.setText(_translate("MainWindow", "view"))
        self.actionadd.setText(_translate("MainWindow", "add"))
        self.actionedit.setText(_translate("MainWindow", "edit"))
        self.actionplaylist.setText(_translate("MainWindow", "playlist"))
        self.actionprofile.setText(_translate("MainWindow", "profile"))
        self.actionDefault.setText(_translate("MainWindow", "Default"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))